name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Dash Desktop ${{ github.ref_name }}'
          releaseBody: |
            ## Dash Desktop ${{ github.ref_name }}
            
            ### Download Options
            Choose the appropriate version for your operating system:
            - Windows: `.msi` installer
            - macOS: `.dmg` installer
            - Linux: `.deb` package and `.AppImage`
            
            ### Installation
            1. Download the appropriate file for your OS
            2. Run the installer
            3. Follow the on-screen instructions
            
            ### System Requirements
            - Windows 10/11
            - macOS 10.15+
            - Ubuntu 20.04 or compatible Linux distribution
            
            ### Support
            If you encounter any issues, please open an issue on GitHub.
            
            ---
            Release Date: ${{ github.event.repository.updated_at }}
          releaseDraft: false
          prerelease: false